//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account_tbl()
        {
            this.Owner_tbl = new HashSet<Owner_tbl>();
        }
    
        public int AccountID { get; set; }
        public string AccountName { get; set; }
        public string Currency { get; set; }
        public string AccountType { get; set; }
        public Nullable<decimal> TransferAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Owner_tbl> Owner_tbl { get; set; }
    }
}
